
export const CarDetails = [
    {
        id: 1,
        name: "Skoda Rapido",
        image: "https://cdni.autocarindia.com/Utils/ImageResizer.ashx?n=http://cms.haymarketindia.net/model/uploads/modelimages/RapidModelImage.jpg&w=730&h=484&q=75&c=1",
        location: "Mumbai",
        price: 3500,
        transmission:"Manual",
        freekms:60,
        seats:5,
        cartype:"Sedan",
        DeliveryType:"Home Delivery",
    },
    {
        id: 2,
        name: "Maruti Dzire",
        image: "https://www.indusmotor.com/public/uploads/Model/417220210526171535.jpg",
        location: "Mumbai",
        price: 1810,
        transmission:"Manual",
        freekms:120,
        seats:5,
        cartype:"Hatchback",
        DeliveryType:"Home Delivery",
    },
    {
        id: 3,
        name: "Hyundai Xcent",
        image: "https://imgd.aeplcdn.com/1056x594/n/2fhd7sa_1471629.jpg?q=85",
        location: "Mumbai",
        price: 1632,
        transmission:"Manual",
        freekms:120,
        seats:5,
        cartype:"Sedan",
        DeliveryType:"Home Delivery",
    },
    {
        id: 4,
        name: "Renault Lodgy",
        image: "https://imgd.aeplcdn.com/664x374/n/js3bpra_1422088.jpg?q=85",
        location: "Mumbai",
        price: 2589,
        transmission:"Automatic",
        freekms:60,
        seats:7,
        cartype:"SUV",
        DeliveryType:"Airport",
    },
    {
        id: 5,
        name: "Wagon R",
        image: "https://imgd.aeplcdn.com/1056x594/n/h5360sa_1458598.jpg?q=85&wm=1",
        location: "Mumbai",
        price: 4500,
        transmission:"Manual",
        freekms:60,
        seats:5,
        cartype:"Hatchback",
        DeliveryType:"Airport",
    },
    {
        id: 6,
        name: "Renault Triber",
        image: "https://imgd.aeplcdn.com/0x0/n/cw/ec/39276/triber-exterior-right-front-three-quarter-168563.jpeg",
        location: "Mumbai",
        price: 5500,
        transmission:"Automatic",
        freekms:120,
        seats:7,
        cartype:"SUV",
        DeliveryType:"Home Delivery",
    },
    {
        id:7,
        name: "Nissan Micra",
        image: "https://imgd.aeplcdn.com/0x0/cw/ec/35606/Nissan-Micra-Exterior-133100.jpg?wm=0",
        location: "Mumbai",
        price: 1693,
        transmission:"Automatic",
        freekms:60,
        seats:5,
        cartype:"Hatchback",
        DeliveryType:"Home Delivery",
    },
    {
        id:8,
        name: "Volkswagen Vento",
        image: "https://imgd.aeplcdn.com/664x374/cw/ec/26563/Volkswagen-Vento-Right-Front-Three-Quarter-169094.jpg?wm=0&q=85",
        location: "Mumbai",
        price: 3865,
        transmission:"Automatic",
        freekms:60,
        seats:5,
        cartype:"Sedan",
        DeliveryType:"Airport",
    },
    {
        id: 9,
        name: "Mahindra XUV700",
        image: "https://stimg.cardekho.com/images/carexteriorimages/630x420/Mahindra/XUV700/8620/1633939302512/front-left-side-47.jpg?tr=w-456",
        location: "Mumbai",
        price: 6500,
        transmission:"Manual",
        freekms:120,
        seats:7,
        cartype:"SUV",
        DeliveryType:"Home Delivery",
    },
    {
        id:10,
        name: "Tata Tiago",
        image: "https://stimg.cardekho.com/images/carexteriorimages/630x420/Tata/Tiago/7381/1617960171816/front-left-side-47.jpg?tr=w-456",
        location: "Mumbai",
        price: 3893,
        transmission:"Automatic",
        freekms:60,
        seats:5,
        cartype:"Hatchback",
        DeliveryType:"Airport",
    },
    {
        id:11,
        name: "Maruti Baleno",
        image: "https://www.rushlane.com/wp-content/uploads/2020/11/2020-maruti-baleno-rs-new-variant.jpg",
        location: "Mumbai",
        price: 1500,
        transmission:"Automatic",
        freekms:60,
        seats:5,
        cartype:"Sedan",
        DeliveryType:"Home Delivery",
    },
    {
        id:12,
        name: "Kia Seltos",
        image: "https://imgd.aeplcdn.com/1200x900/n/cw/ec/33372/seltos-exterior-right-front-three-quarter-3.jpeg?q=85",
        location: "Mumbai",
        price: 6865,
        transmission:"Manual",
        freekms:120,
        seats:7,
        cartype:"SUV",
        DeliveryType:"Airport",
    },
];